INSERT INTO t1(USERNAME, PASSWORD, ENABLED) VALUES (1,1,1);
INSERT INTO T2 (USERNAME, AUTHORITY) VALUES ('fd', 'fd');
INSERT INTO T3 (C1, C2) VALUES ('ew1', 'ew');
INSERT INTO T3 (C1, C2) VALUES ('ew2', 'ew');
INSERT INTO T3 (C1, C2) VALUES ('ew3', 'ew');